apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: flanksource-ci-runner-deployment
  namespace: github-runner
spec:
  replicas: 2
  template:
     spec:
      image: flanksource/build-tools:v0.10.2
      organization: flanksource
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: flanksource-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: flanksource-ci-runner-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - flanksource/karina

