apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: flanksource-ci-runner-deployment
  namespace: github-runner
spec:
  replicas: 4
  template:
    spec:
      labels:
        - self-hosted
      containers:
        - name: runner
          image: flanksource/build-tools:v0.10.8
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /runner/_work
              name:      work
            - mountPath: /runner/externals
              name:      externals
            - mountPath: /certs/client
              name:      certs-client
            - mountPath: /lib/modules
              name:      modules
              readOnly:  true
            - mountPath: /sys/fs/cgroup
              name:      cgroup
          securityContext:
            runAsGroup: 0
        - name: docker
          image: docker:dind
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /runner/_work
              name:      work
            - mountPath: /runner/externals
              name:      externals
            - mountPath: /certs/client
              name:      certs-client
            - mountPath: /lib/modules
              name:      modules
              readOnly:  true
            - mountPath: /sys/fs/cgroup
              name:      cgroup
          securityContext:
            privileged: true
          args: ["--dns", "8.8.8.8"]
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
      organization: flanksource
      dockerdWithinRunnerContainer: false
      dockerenabled: true
      env:
        - name: RUNNER_NAME
          value: flanksource-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: flanksource-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: flanksource-ci-runner-deployment
  minReplicas: 4
  maxReplicas: 8
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - karina
