apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/flanksource/actions-runner-controller/config/default?ref=v0.9.5-flanksource
resources:
  - github-runner-deployment.yaml
  - runner-secrets.yaml
images:
- name: summerwind/actions-runner-controller
  newName: flanksource/actions-runner-controller
  newTag: v0.9.5-flanksource
