apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/summerwind/actions-runner-controller/tree/master/config/default?ref=v0.16.0
resources:
  - github-runner-deployment.yaml
  - runner-secrets.yaml
