apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: github-runner
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AQCCaJ1vlnORgEjbG2N8UdYpFiXd3CPr12zdc+lBIcpAeXs2orKxUugWGiNG8NB7rB/46bWccOZ2OJUkFHCgFFxmomqbDdIshY9dWmz8zyaD/xDRy4qOUDhPjj80KlRDC58ygkWUcE5S1GQAVFkQbZLwIVlJS7vWvjT9soMXTQj5eOW6lxgRJl5cOXZDXCEkRo+DOquS9OmqHFb4AWSV67zN+f/P4dEWLx9/Hd2h7HSS4/lx+MeTvYDqrWhmB2x9wXubMoUKCG3mAzIYaDYWFBoE5rhDPqbX402uplGMG5b9OWLuV8dEqfr86MY2i8f8FzUEZM73e7vtNClxAihsL+N5IHHhoTHvUlK/PxUlVMHHXcsrCgUM50PtaHpVMMvZQpqgKMNR
    AWS_SECRET_ACCESS_KEY: AQBeazbUmYjNfQBladIAOuD5kdRuczw2c/J65UyeJxzP7sAyOzDqfvMETXu0QRRPrnfYciZM94Cr/ehEXMZVazogshHYwyNc3PhDW8aU7FWaXz7VAL2isZZKpb/mmH7N9c262njvfOcA/+QIzCgPJnrTZBQ0iN3Pk40Y71ZuAqrcL0HeuAlk5Anx0J4d6EfLIDfb/SvzRsSyeuYKbyTwZc8EqHtQxeNY8CvQq665vyECOFvKm/1c5dDA1Cj2yKd0iLlqMpkm0fUi8sHSyovIvlRqGXNhFghRdeXoOEuV/S1lgpnf9HR+uwKqAtcKxWqIlFEuLZbVf/uXxSuDTHl2HEJl6l+mgeB9CXVJe6P+HHUj9XWquJIfw+Dl2pmzcJ+v8DRpe0kAYlzJWhsR1r2wuG80wWIbQ0hGv4Q=
    GITHUB_TOKEN: AQBmuDUSkLFklFRHscsGGIs5jsjOITYAwyTAvPShumSpz4grSigQscXFfqcZgomvw5watupDkz2mOL5+2yhAhIs9uvLrTXxhamtq4tmwH87PbwQBmkDtTUIztxFgmqqSS6Me8r1/MYTIDrI3t6fBiInlUllOBdkpgydZcmnMc72wFD5dAbMTWYRRIChUsClJROPcCM/CLchaAOamf8Pgfv2ZMxeHjvDpRuQYve0X023QCvqaFHPxuU2utw70w2HGN9Pdb0LXQ6ECnr5OIixZ9/pV+2QZfmfZAAjl6RHH4k91YJDOYFqo/1FJ42PDaNSXJDgQnxIDmdkoRpFtSBBp9Sq4ngOoWdhiLkGYk/YRAefzFeQaNsOs4i0zkeGbNLGvXSQbIep2V1if84ceJflI8enPFWMwbJQsePc=
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: github-runner
